[Distribution]
Distribution=arch

[Output]
Format=disk
ImageId=organ
SplitArtifacts=

[Content]
Packages=base
	linux-rt
	linux-firmware
	systemd-ukify
	pipewire-jack
	openssh
	neovim
	polkit
	dhcpcd
	pipewire-alsa
	usbutils
	alsa-utils
	less
	nano
	calf
	rtkit
	intel-ucode
	amd-ucode
WithDocs=false
ExtraTrees=
	registers/:/home/organ/registers/
	target/release/organ:/home/organ/organ
	mkosi.repart/:/usr/lib/repart.d/
Bootable=yes
RootPassword=organ
KernelCommandLine=nowatchdog processor.max_cstate=1 pcie_aspm=performance quiet rw preempt=full threadirqs nopti systemd.volatile=overlay
Timezone=UTC
Hostname=organ

[Build]
ToolsTree=yes
ToolsTreeDistribution=arch
ToolsTreePackages=rustup
	alsa-lib
	pipewire-jack
	clang
ToolsTreeProfiles=devel
	misc
	package-manager
	runtime
RepartOffline=yes
WithNetwork=yes
BuildSources=.
BuildDirectory=target

[Runtime]
CPUs=4
RAM=12G
QemuArgs=-net user,hostfwd=tcp::2222-:22
